// <auto-generated />
namespace Portugal_Insurance___PayPal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changed_Transaction_Id_Field_To_payPalTransactionId_in_AutomobilePolicy_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_Transaction_Id_Field_To_payPalTransactionId_in_AutomobilePolicy_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201612080708412_changed_Transaction_Id_Field_To_payPalTransactionId_in_AutomobilePolicy_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
