// <auto-generated />
namespace Portugal_Insurance___PayPal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changed_policyTotalCost_field_from_double_to_decimal_AutomobilePolicy_Controller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_policyTotalCost_field_from_double_to_decimal_AutomobilePolicy_Controller));
        
        string IMigrationMetadata.Id
        {
            get { return "201612050909108_changed_policyTotalCost_field_from_double_to_decimal_AutomobilePolicy_Controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
